// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "VTestHarness__Syms.h"
#include "VTestHarness.h"
#include "VTestHarness___024root.h"
#include "VTestHarness___024unit.h"

void VTestHarness__Syms::VTestHarness__Syms_2() {
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__reservation_station__assert___05Fassert_7.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.reservation_station.assert__assert_7", "assert__assert_7", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__reservation_station__assert___05Fassert_8.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.reservation_station.assert__assert_8", "assert__assert_8", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad", "spad", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__acc_mems_0.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.acc_mems_0", "acc_mems_0", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__acc_mems_0__mem.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.acc_mems_0.mem", "mem", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__acc_mems_1.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.acc_mems_1", "acc_mems_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__acc_mems_1__mem.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.acc_mems_1.mem", "mem", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__buffer_1__monitor.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.buffer_1.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__buffer_2__monitor.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.buffer_2.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__buffer__monitor.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.buffer.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__mvin_scale_pixel_repeater.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.mvin_scale_pixel_repeater", "mvin_scale_pixel_repeater", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__reader__xactTracker.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.reader.xactTracker", "xactTracker", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__reader__xactTracker__assert___05Fassert.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.reader.xactTracker.assert__assert", "assert__assert", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__spad_mems_0.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.spad_mems_0", "spad_mems_0", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__spad_mems_1.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.spad_mems_1", "spad_mems_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__spad_mems_2.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.spad_mems_2", "spad_mems_2", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__spad_mems_3.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.spad_mems_3", "spad_mems_3", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__widget__monitor.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.widget.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__writer.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.writer", "writer", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__xbar.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.xbar", "xbar", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__xbar__monitor.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.xbar.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__xbar__monitor_1.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.xbar.monitor_1", "monitor_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__spad__zero_writer_pixel_repeater.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.spad.zero_writer_pixel_repeater", "zero_writer_pixel_repeater", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__store_controller.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.store_controller", "store_controller", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__store_controller__cmd_tracker.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.store_controller.cmd_tracker", "cmd_tracker", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__store_controller__cmd_tracker__assert___05Fassert.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.store_controller.cmd_tracker.assert__assert", "assert__assert", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__gemmini__tlb__tlbs_0.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.gemmini.tlb.tlbs_0", "tlbs_0", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__lsu.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.lsu", "lsu", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__lsu__assert___05Fassert_28.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.lsu.assert__assert_28", "assert__assert_28", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__lsu__assert___05Fassert_49.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.lsu.assert__assert_49", "assert__assert_49", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__lsu__assert___05Fassert_51.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.lsu.assert__assert_51", "assert__assert_51", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__lsu__dtlb.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.lsu.dtlb", "dtlb", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__ptw.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.ptw", "ptw", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__tlMasterXbar.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.tlMasterXbar", "tlMasterXbar", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__tlMasterXbar__monitor.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.tlMasterXbar.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain_boom_tile__tlMasterXbar__monitor_1.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain_boom_tile.tlMasterXbar.monitor_1", "monitor_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tlDM__dmInner__dmInner.configure(this, name(), "TestHarness.chiptop.system.tlDM.dmInner.dmInner", "dmInner", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tlDM__dmInner__dmInner__monitor.configure(this, name(), "TestHarness.chiptop.system.tlDM.dmInner.dmInner.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tlDM__dmInner__dmInner__monitor_1.configure(this, name(), "TestHarness.chiptop.system.tlDM.dmInner.dmInner.monitor_1", "monitor_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tlDM__dmOuter__asource__monitor.configure(this, name(), "TestHarness.chiptop.system.tlDM.dmOuter.asource.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tlDM__dmOuter__dmOuter__monitor.configure(this, name(), "TestHarness.chiptop.system.tlDM.dmOuter.dmOuter.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tlDM__dmOuter__dmiBypass__bar__monitor.configure(this, name(), "TestHarness.chiptop.system.tlDM.dmOuter.dmiBypass.bar.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tlDM__dmOuter__dmiBypass__error__monitor.configure(this, name(), "TestHarness.chiptop.system.tlDM.dmOuter.dmiBypass.error.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tlDM__dmOuter__dmiXbar.configure(this, name(), "TestHarness.chiptop.system.tlDM.dmOuter.dmiXbar", "dmiXbar", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tlDM__dmOuter__dmiXbar__monitor.configure(this, name(), "TestHarness.chiptop.system.tlDM.dmOuter.dmiXbar.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tsi_domain__buffer__monitor.configure(this, name(), "TestHarness.chiptop.system.tsi_domain.buffer.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tsi_domain__serdesser__monitor.configure(this, name(), "TestHarness.chiptop.system.tsi_domain.serdesser.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__uartClockDomainWrapper__uart_0__monitor.configure(this, name(), "TestHarness.chiptop.system.uartClockDomainWrapper.uart_0.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__adapter.configure(this, name(), "TestHarness.ram.adapter", "adapter", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__buffer_1__monitor.configure(this, name(), "TestHarness.ram.buffer_1.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__buffer__monitor.configure(this, name(), "TestHarness.ram.buffer.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__fragmenter.configure(this, name(), "TestHarness.ram.fragmenter", "fragmenter", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__fragmenter_1.configure(this, name(), "TestHarness.ram.fragmenter_1", "fragmenter_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__fragmenter_1__monitor.configure(this, name(), "TestHarness.ram.fragmenter_1.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__fragmenter__monitor.configure(this, name(), "TestHarness.ram.fragmenter.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__rom__monitor.configure(this, name(), "TestHarness.ram.rom.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__serdesser__monitor.configure(this, name(), "TestHarness.ram.serdesser.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__srams.configure(this, name(), "TestHarness.ram.srams", "srams", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__srams__monitor.configure(this, name(), "TestHarness.ram.srams.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__xbar.configure(this, name(), "TestHarness.ram.xbar", "xbar", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__xbar__monitor.configure(this, name(), "TestHarness.ram.xbar.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__uart_sim_0.configure(this, name(), "TestHarness.uart_sim_0", "uart_sim_0", -9, VerilatedScope::SCOPE_OTHER);

    // Set up scope hierarchy

}
